name: Build and Publish

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'claude-input.log'
  workflow_dispatch:
    inputs:
      fetch_website:
        description: 'Fetch data from website'
        required: false
        type: boolean
        default: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ZgBibliobusTimeTable.sln
      
    - name: Create templates directory
      run: |
        mkdir -p templates
        cp templates/index.html templates/
        cp templates/styles.css templates/
      
    - name: Enable website fetching if selected
      if: ${{ inputs.fetch_website }}
      run: |
        sed -i 's/\/\/>>> uncomment >>>//' ZgBibliobusTimeTable/Program.cs
      
    - name: Prepare sample data file
      run: |
        # Download sample content for testing
        # We don't need to create directories as our updated code handles this
        wget -O sample_data.html "https://www.kgz.hr/hr/knjiznice/bibliobusna-sluzba/raspored-bibliobusnih-stajalista/65960"
        
    - name: Run application
      run: |
        # Build the application first
        dotnet build ZgBibliobusTimeTable/ZgBibliobusTimeTable.csproj --configuration Release
        
        # Find the output directory where the app is built
        APP_DIR=$(find ZgBibliobusTimeTable/bin -name "net9.0" -type d)
        
        # Create templates directory in the build output dir
        mkdir -p "$APP_DIR/templates"
        
        # Copy the template files
        cp templates/* "$APP_DIR/templates/"
        
        # Create Data directory in the build output dir
        mkdir -p "$APP_DIR/Data"
        
        # Copy the sample data
        cp sample_data.html "$APP_DIR/Data/index.html"
        
        # Run the application
        dotnet run --project ZgBibliobusTimeTable/ZgBibliobusTimeTable.csproj --configuration Release --no-build
      
    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: bibliobus-website
        path: |
          ZgBibliobusTimeTable/bin/Release/net9.0/website/
        
    - name: Deploy to GitHub Pages
      run: |
        # Create a temporary git repository
        WEBSITE_DIR=$(find ZgBibliobusTimeTable/bin -name "website" -type d)
        
        if [ -z "$WEBSITE_DIR" ]; then
          echo "Error: Website directory not found"
          exit 1
        fi
        
        echo "Deploying website from $WEBSITE_DIR"
        
        # Configure git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Create and checkout pages branch
        git checkout --orphan pages
        
        # Remove everything
        git rm -rf .
        
        # Copy website files
        cp -r "$WEBSITE_DIR"/* .
        
        # Add README
        echo "# Zagreb Bibliobus Timetable" > README.md
        echo "This is an automatically generated website for the Zagreb Bibliobus (mobile library) timetable." >> README.md
        echo "Data is sourced from the official website: https://www.kgz.hr/" >> README.md
        echo "Last updated: $(date)" >> README.md
        
        # Add all files
        git add .
        
        # Commit changes
        git commit -m "Update website $(date)"
        
        # Push to GitHub
        git push -f origin pages